### ISSUE TITLE
Removing console.logs and creating a type definition file

### ISSUE THREAD

**Issue by LongNguyen206** [renrizzolo/react-native-swipeable-rating#1]
hey @renrizzolo, thank you for this awesome component. It is exactly what i needed. There are a few minor changes I can offer:
1) removing console.logs in the js file
2) adding a prop type file for typescript

 I have done both on my forked repo and would love to send you a PR if thats ok.

**Comment by renrizzolo** [comment]
Sounds good to me! Thanks!
